import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { FileSpreadsheet, ArrowLeft, Download, FileUp, HelpCircle, ChevronDown, ChevronUp, FileText, ArrowRightLeft, Copy, Check, FileJson } from 'lucide-react';
import { Link } from 'react-router-dom';
import { cn } from '@/src/lib/utils';

const FAQS = [
  {
    question: "How to convert CSV to Markdown?",
    answer: "To convert CSV to Markdown, paste your CSV data into the input area or upload a .csv file. Our tool will automatically format the data into a clean Markdown table. You can then copy the result or download it as a .md file."
  },
  {
    question: "How to convert a CSV to Markdown with custom delimiters?",
    answer: "Currently, our tool supports standard comma-separated values (CSV). It uses the first row as the table header and subsequent rows as table data."
  },
  {
    question: "How to convert CSV into Markdown for GitHub?",
    answer: "The Markdown generated by this tool is fully compatible with GitHub, GitLab, and other platforms that support GFM (GitHub Flavored Markdown) tables."
  },
  {
    question: "Can I convert a Markdown file to CSV?",
    answer: "Yes! You can switch to the 'Markdown to CSV' mode. Paste your Markdown table, and the tool will extract the data and convert it into a standard CSV format."
  },
  {
    question: "How to convert CSV to Markdown online for free?",
    answer: "OmniTool provides a 100% free, private, and secure online converter. All processing happens in your browser, so your data never leaves your device."
  }
];

export const CsvToMarkdown = () => {
  const [inputData, setInputData] = useState('');
  const [isProcessing, setIsProcessing] = useState(false);
  const [openFaq, setOpenFaq] = useState<number | null>(0);
  const [mode, setMode] = useState<'csv-to-md' | 'md-to-csv'>('csv-to-md');
  const [copied, setCopied] = useState(false);

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (event) => {
      setInputData(event.target?.result as string);
    };
    reader.readAsText(file);
  };

  const convertData = () => {
    if (!inputData.trim()) return;
    setIsProcessing(true);

    try {
      if (mode === 'csv-to-md') {
        const lines = inputData.trim().split('\n');
        if (lines.length === 0) throw new Error('Empty CSV');

        const rows = lines.map(line => line.split(',').map(cell => cell.trim()));
        const headers = rows[0];
        const dataRows = rows.slice(1);

        let markdown = `| ${headers.join(' | ')} |\n`;
        markdown += `| ${headers.map(() => '---').join(' | ')} |\n`;
        dataRows.forEach(row => {
          markdown += `| ${row.join(' | ')} |\n`;
        });

        downloadFile(markdown, 'table.md', 'text/markdown');
      } else {
        const lines = inputData.trim().split('\n').filter(line => line.includes('|'));
        if (lines.length < 3) throw new Error('Invalid Markdown table');

        // Skip header separator line (usually | --- | --- |)
        const rows = lines.filter((_, i) => i !== 1).map(line => {
          return line.split('|')
            .filter((cell, i, arr) => i > 0 && i < arr.length - 1)
            .map(cell => cell.trim());
        });

        const csvContent = rows.map(row => row.join(',')).join('\n');
        downloadFile(csvContent, 'data.csv', 'text/csv');
      }
    } catch (error) {
      alert('Error processing data. Please check your input format.');
      console.error(error);
    } finally {
      setIsProcessing(false);
    }
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(inputData);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadFile = (content: string, fileName: string, contentType: string) => {
    const blob = new Blob([content], { type: contentType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = fileName;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-4xl mx-auto px-4 pt-24 pb-12">
      <Link to="/" className="inline-flex items-center gap-2 text-zinc-500 hover:text-zinc-900 mb-8 transition-colors group">
        <ArrowLeft className="w-4 h-4 transition-transform group-hover:-translate-x-1" />
        Back to Tools
      </Link>

      <div className="text-center mb-12">
        <div className="w-16 h-16 bg-blue-50 rounded-2xl flex items-center justify-center mx-auto mb-4">
          <FileText className="w-8 h-8 text-blue-600" />
        </div>
        <h1 className="text-4xl font-bold text-zinc-900 mb-4">CSV to Markdown Converter</h1>
        <p className="text-zinc-600 max-w-2xl mx-auto">
          The best <strong>CSV to Markdown</strong> tool. Easily <strong>convert CSV to Markdown</strong> or use our <strong>markdown to csv converter</strong> for free.
        </p>
      </div>

      <div className="bg-white p-8 rounded-3xl border border-zinc-200 shadow-sm mb-12">
        <div className="flex items-center justify-center gap-4 mb-8">
          <button
            onClick={() => setMode('csv-to-md')}
            className={cn(
              "px-6 py-2 rounded-xl font-medium transition-all",
              mode === 'csv-to-md' ? "bg-zinc-900 text-white shadow-lg" : "bg-zinc-100 text-zinc-600 hover:bg-zinc-200"
            )}
          >
            CSV to Markdown
          </button>
          <ArrowRightLeft className="w-5 h-5 text-zinc-300" />
          <button
            onClick={() => setMode('md-to-csv')}
            className={cn(
              "px-6 py-2 rounded-xl font-medium transition-all",
              mode === 'md-to-csv' ? "bg-zinc-900 text-white shadow-lg" : "bg-zinc-100 text-zinc-600 hover:bg-zinc-200"
            )}
          >
            Markdown to CSV
          </button>
        </div>

        <div className="space-y-6">
          <div className="relative">
            <textarea
              value={inputData}
              onChange={(e) => setInputData(e.target.value)}
              placeholder={mode === 'csv-to-md' ? "Paste your CSV here (e.g., Name, Age, City)..." : "Paste your Markdown table here..."}
              className="w-full h-64 p-6 bg-zinc-50 border border-zinc-200 rounded-2xl focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 transition-all font-mono text-sm"
            />
            <div className="absolute top-4 right-4 flex gap-2">
              <button
                onClick={copyToClipboard}
                className="p-2 bg-white border border-zinc-200 rounded-lg text-zinc-600 hover:bg-zinc-50 transition-colors shadow-sm"
                title="Copy to clipboard"
              >
                {copied ? <Check className="w-4 h-4 text-emerald-500" /> : <Copy className="w-4 h-4" />}
              </button>
              <input
                type="file"
                accept={mode === 'csv-to-md' ? ".csv" : ".md"}
                onChange={handleFileUpload}
                className="hidden"
                id="file-upload"
              />
              <label
                htmlFor="file-upload"
                className="flex items-center gap-2 px-4 py-2 bg-white border border-zinc-200 rounded-lg text-sm font-medium text-zinc-600 hover:bg-zinc-50 cursor-pointer transition-colors shadow-sm"
              >
                <FileUp className="w-4 h-4" />
                Upload
              </label>
            </div>
          </div>

          <button
            onClick={convertData}
            disabled={!inputData.trim() || isProcessing}
            className="w-full py-4 bg-blue-600 text-white rounded-2xl font-bold hover:bg-blue-700 transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2 shadow-lg shadow-blue-600/20"
          >
            {isProcessing ? 'Processing...' : (
              <>
                <Download className="w-5 h-5" />
                {mode === 'csv-to-md' ? 'Convert CSV to Markdown' : 'Convert Markdown to CSV'}
              </>
            )}
          </button>
        </div>
      </div>

      {/* SEO Content Section */}
      <div className="prose prose-zinc max-w-none mb-16">
        <h2 className="text-2xl font-bold text-zinc-900 mb-4">Professional CSV Format to Markdown Conversion</h2>
        <p className="text-zinc-600 leading-relaxed">
          Need to display your data on GitHub or a blog? Our <strong>CSV to Markdown</strong> converter transforms your raw <strong>CSV format to Markdown</strong> tables in seconds. It's the perfect <strong>markdown to csv converter</strong> for developers and content creators who need to move data between spreadsheets and documentation. Whether you are looking for <strong>Markdown CSV to</strong> conversion or the other way around, OmniTool handles it with ease.
        </p>
      </div>

      {/* FAQ Section */}
      <div className="mb-16">
        <h2 className="text-2xl font-bold text-zinc-900 mb-8 flex items-center gap-2">
          <HelpCircle className="w-6 h-6 text-blue-500" />
          Frequently Asked Questions
        </h2>
        <div className="space-y-4">
          {FAQS.map((faq, index) => (
            <div 
              key={index}
              className="border border-zinc-200 rounded-2xl overflow-hidden bg-white"
            >
              <button
                onClick={() => setOpenFaq(openFaq === index ? null : index)}
                className="w-full px-6 py-4 flex items-center justify-between text-left hover:bg-zinc-50 transition-colors"
              >
                <span className="font-bold text-zinc-900">{faq.question}</span>
                {openFaq === index ? <ChevronUp className="w-5 h-5 text-zinc-400" /> : <ChevronDown className="w-5 h-5 text-zinc-400" />}
              </button>
              <AnimatePresence>
                {openFaq === index && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: 'auto', opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    className="overflow-hidden"
                  >
                    <div className="px-6 pb-4 text-zinc-600 leading-relaxed">
                      {faq.answer}
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          ))}
        </div>
      </div>

      {/* Related Tools */}
      <div className="border-t border-zinc-200 pt-12">
        <h3 className="text-lg font-bold text-zinc-900 mb-6">Related Data Tools</h3>
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4">
          <Link to="/json-to-csv" className="p-4 bg-white border border-zinc-200 rounded-xl hover:border-blue-500 transition-colors flex items-center gap-3">
            <div className="w-10 h-10 bg-amber-50 rounded-lg flex items-center justify-center">
              <FileSpreadsheet className="w-5 h-5 text-amber-600" />
            </div>
            <span className="font-medium text-zinc-900">JSON to CSV</span>
          </Link>
          <Link to="/json-formatter" className="p-4 bg-white border border-zinc-200 rounded-xl hover:border-blue-500 transition-colors flex items-center gap-3">
            <div className="w-10 h-10 bg-purple-50 rounded-lg flex items-center justify-center">
              <FileJson className="w-5 h-5 text-purple-600" />
            </div>
            <span className="font-medium text-zinc-900">JSON Formatter</span>
          </Link>
          <Link to="/text-converter" className="p-4 bg-white border border-zinc-200 rounded-xl hover:border-blue-500 transition-colors flex items-center gap-3">
            <div className="w-10 h-10 bg-indigo-50 rounded-lg flex items-center justify-center">
              <ArrowRightLeft className="w-5 h-5 text-indigo-600" />
            </div>
            <span className="font-medium text-zinc-900">Text Converter</span>
          </Link>
        </div>
      </div>
    </div>
  );
};
